userName: YOUR_USERNAME
accessKey: YOUR_ACCESS_KEY

projectName: BrowserStack Samples
buildName: behave-playwright-sdk-build-1
buildIdentifier: '#${BUILD_NUMBER}'

framework: behave

# Single-platform run: one chromium session, no parallelism.
platforms:
  - os: Windows
    osVersion: 11
    browserName: chrome
    browserVersion: latest

parallelsPerPlatform: 1

browserstackLocal: false

debug: true
networkLogs: false
consoleLogs: errors

source: behave-playwright-sdk:sample-master:v1.0
